export enum Dependencies {
    AdvancedQueryService,
    ApiHelperService,
    ClubService,
    CompetitionService,
    DateSource,
    GameService,
    GameEventService,
    GamePlayerService,
    PersonService,
    ProfileService,
    SeasonService,
    UuidSource,
    VenueService,
};