import { Tendency } from "@src/model/type/tendency";
import { GameStatus } from "@src/model/type/game-status";
import { DateString } from "@src/util/domain-types";

export interface Game {
    id: number;
    kickoff: DateString;
    resultTendency: Tendency;
    opponentId: number;
    competitionId: number;
    competitionRound: string;
    competitionStage: string;
    seasonId: number;
    status: GameStatus;
    venueId: number;
    isHomeTeam: boolean;
    attendance: number;
    fullTimeGoalsMain: number;
    fullTimeGoalsOpponent: number;
    halfTimeGoalsMain: number;
    halfTimeGoalsOpponent: number;
    tacticalFormationMain?: string;
    tacticalFormationOpponent?: string;
    yellowCardsMain: number;
    yellowCardsOpponent: number;
    yellowRedCardsMain: number;
    yellowRedCardsOpponent: number;
    redCardsMain: number;
    redCardsOpponent: number;
    penaltiesScoredMain: number;
    penaltiesScoredOpponent: number;
    penaltiesMissedMain: number;
    penaltiesMissedOpponent: number;
    ownGoalsMain: number;
    ownGoalsOpponent: number;
    turnaroundsMain: number;
    turnaroundsOpponent: number;
    directFreeKickGoalsMain: number;
    directFreeKickGoalsOpponent: number;
    bicycleKickGoalsMain: number;
    bicycleKickGoalsOpponent: number;
    tablePositionMainBefore?: number;
    tablePositionOpponentBefore?: number;
    tablePositionMainAfter?: number;
    tablePositionOpponentAfter?: number;
    tablePositionOffset: number;
    isSoldOut: boolean;
    leg?: number;
    previousLeg?: number;
    aetGoalsMain?: number;
    aetGoalsOpponent?: number;
    psoGoalsMain?: number;
    psoGoalsOpponent?: number;
    isPractice: boolean;
    scheduled?: Date;
    isNeutralGround: boolean;
    titleWinningGame: boolean;
    titleCount?: number;
}